create table if not exists public.pb_medicines (
  id bigint generated by default as identity primary key,
  name text not null,
  brand text not null,
  category text not null,
  price numeric(12,2) not null default 0,
  quantity integer not null default 0,
  expiry_date date not null,
  batch_no text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.pb_customers (
  id bigint generated by default as identity primary key,
  name text not null,
  phone text not null,
  email text not null default '',
  address text not null default '',
  created_at timestamptz not null default now()
);

create table if not exists public.pb_bills (
  id bigint generated by default as identity primary key,
  customer_id bigint not null references public.pb_customers(id) on delete restrict,
  customer_name text not null,
  items jsonb not null,
  total numeric(12,2) not null,
  tax numeric(12,2) not null,
  grand_total numeric(12,2) not null,
  date timestamptz not null default now()
);

create table if not exists public.pb_staffs (
  id bigint generated by default as identity primary key,
  staff_id text not null unique,
  name text not null,
  username text not null unique,
  password text not null,
  created_at timestamptz not null default now(),
  created_by text not null default 'admin',
  active boolean not null default true
);

create table if not exists public.pb_staff_history (
  id bigint generated by default as identity primary key,
  action text not null check (action in ('ADDED', 'DELETED')),
  staff_id text not null,
  name text not null,
  username text not null,
  performed_by text not null,
  performed_at timestamptz not null default now()
);

alter table public.pb_medicines enable row level security;
alter table public.pb_customers enable row level security;
alter table public.pb_bills enable row level security;
alter table public.pb_staffs enable row level security;
alter table public.pb_staff_history enable row level security;

drop policy if exists "Allow all reads medicines" on public.pb_medicines;
drop policy if exists "Allow all writes medicines" on public.pb_medicines;
create policy "Allow all reads medicines" on public.pb_medicines for select using (true);
create policy "Allow all writes medicines" on public.pb_medicines for all using (true) with check (true);

drop policy if exists "Allow all reads customers" on public.pb_customers;
drop policy if exists "Allow all writes customers" on public.pb_customers;
create policy "Allow all reads customers" on public.pb_customers for select using (true);
create policy "Allow all writes customers" on public.pb_customers for all using (true) with check (true);

drop policy if exists "Allow all reads bills" on public.pb_bills;
drop policy if exists "Allow all writes bills" on public.pb_bills;
create policy "Allow all reads bills" on public.pb_bills for select using (true);
create policy "Allow all writes bills" on public.pb_bills for all using (true) with check (true);

drop policy if exists "Allow all reads staffs" on public.pb_staffs;
drop policy if exists "Allow all writes staffs" on public.pb_staffs;
create policy "Allow all reads staffs" on public.pb_staffs for select using (true);
create policy "Allow all writes staffs" on public.pb_staffs for all using (true) with check (true);

drop policy if exists "Allow all reads staff history" on public.pb_staff_history;
drop policy if exists "Allow all writes staff history" on public.pb_staff_history;
create policy "Allow all reads staff history" on public.pb_staff_history for select using (true);
create policy "Allow all writes staff history" on public.pb_staff_history for all using (true) with check (true);
